language: python

python:
    - 2.7
    - 3.5
    - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: alexbahnisch
    password:
      secure: dN1TiYB9fbivJc0mmlVh/W+hmbaVdiCTAgXTfAnx5sd2Xxp/vCI1ybbHuwhD8bTnhZItbw04SU0wQnYRcu6O/I6C6ddFUv+d92fgCUlf+NtP7g3J34aMLVUJPheagA72Vs/KT/ZOWmNUyB34lywREvzCvvI4jRVkUj3SgW44E8eVlHkW0MdjeItsraB/hSiXy5YhO2R6FF5Stc1zoaKBg1ljhJNKV4V3JfoPhPtZhlOX3+zWxx1jaTMUz6/Zdi16I+NLzxCKvvh+gcemxWHFSWHhXkw7ycBH2gel93xLS68nJ0GGlYvAY9sFV8yLSkv6njV98IngyZFacquTOsQYni5YVu4xHpPi0NBlHU/LRVLCGpbIbY4MbWGsNBI8WesebkdPZbswKBWqeowrRwQxtc06n0fGDoW74XevmPLI2hTVwsP3rjdLhsoz7hHxSky2iU8a/x3Dua1sBeds1S59VusGih8r4XkeFDGOnQdD3b5fW+72MUonZF9fsvcAQjBKRbgTkVKpN9b7TFuQnKnbZwEeCzdfyMeAzHb6vQmDQBwbrjE7TXkzWeTw0YVaQufXk5iayI9v/uhA7mXNuQFdfwyrAhWtmemX+2N5oGD+Y3r0KI+6Y32rL0jFYrU4N56OnytdDiF9l2unQ8OHjrladITyq3XvpFTAYr177XdtaJk=
    distributions: sdist bdist_wheel
    on:
      branch: master
      python: 3.6
      tags: false

  - provider: pypi
    server: https://upload.pypi.org/legacy/
    user: alexbahnisch
    password:
      secure: dN1TiYB9fbivJc0mmlVh/W+hmbaVdiCTAgXTfAnx5sd2Xxp/vCI1ybbHuwhD8bTnhZItbw04SU0wQnYRcu6O/I6C6ddFUv+d92fgCUlf+NtP7g3J34aMLVUJPheagA72Vs/KT/ZOWmNUyB34lywREvzCvvI4jRVkUj3SgW44E8eVlHkW0MdjeItsraB/hSiXy5YhO2R6FF5Stc1zoaKBg1ljhJNKV4V3JfoPhPtZhlOX3+zWxx1jaTMUz6/Zdi16I+NLzxCKvvh+gcemxWHFSWHhXkw7ycBH2gel93xLS68nJ0GGlYvAY9sFV8yLSkv6njV98IngyZFacquTOsQYni5YVu4xHpPi0NBlHU/LRVLCGpbIbY4MbWGsNBI8WesebkdPZbswKBWqeowrRwQxtc06n0fGDoW74XevmPLI2hTVwsP3rjdLhsoz7hHxSky2iU8a/x3Dua1sBeds1S59VusGih8r4XkeFDGOnQdD3b5fW+72MUonZF9fsvcAQjBKRbgTkVKpN9b7TFuQnKnbZwEeCzdfyMeAzHb6vQmDQBwbrjE7TXkzWeTw0YVaQufXk5iayI9v/uhA7mXNuQFdfwyrAhWtmemX+2N5oGD+Y3r0KI+6Y32rL0jFYrU4N56OnytdDiF9l2unQ8OHjrladITyq3XvpFTAYr177XdtaJk=
    distributions: sdist bdist_wheel
    on:
      branch: master
      python: 3.6
      tags: true
